### ISSUE TITLE
enable webserver with flags

### ISSUE THREAD

**Issue by rezam90** [psi-4ward/docker-powerdns#14]
Hi @psi-4ward.
it might be great if there was a flag for enabling `webserver`. like `--webserver=yes` or something when running docker.

btw, nice job

**Comment by psi-4ward** [comment]
There are different ways to configure pdns.
In your case it would be a way to use cli flags. If the args starts with `--` it gets handed over to pdns so you can use something like

```bash
docker run --name powerdns .... psitrax/powerdns --webserver=yes
```

see https://github.com/psi-4ward/docker-powerdns/blob/master/entrypoint.sh#L51

An other way would be to inject an own pdns.config.

Hope this fits your needs.
