### ISSUE TITLE
Enable dnssec?

### ISSUE THREAD

**Issue by rkerr** [psi-4ward/docker-powerdns#18]
The current container has dnssec disable in pdns.conf. For my needs it would be useful if it instead included gmysql-dnssec=yes but there might be a good reason to have it disabled that I'm not seeing?

**Comment by psi-4ward** [comment]
You can enable bit by passing a cli argument to docker run or use your own pdns.conf. So you're asking regarding the default value?

**Comment by rkerr** [comment]
To be honest I hadn't realised you could pass it on the cli - should pay more attention to the docs, sorry. I think it would still be nice if it was the default, unless there is a good reason not have it enabled?

**Comment by psi-4ward** [comment]
In my op at least for backward compatibility we should not enable it by default.
