### ISSUE TITLE
No license?

### ISSUE THREAD

**Issue by felixsand** [psi-4ward/docker-powerdns#2]
Would be great if you could add what license this uses?
MIT would be nice for example :)

https://choosealicense.com/

**Comment by psi-4ward** [comment]
Hmm a license for a docker image? I think this is not necessary. PowerDNS itself is GPL.

**Comment by felixsand** [comment]
As I've understood it you still need a license for the extra files you've added like entrypoint.sh, etc. I might be wrong though :)
