### ISSUE TITLE
unknown flag: --webserver See 'docker run --help'.

### ISSUE THREAD

**Issue by Hybelkaninen** [psi-4ward/docker-powerdns#26]
Hi, i keep getting error unknown flag when using: --webserver=yes
Can you please show example where the flag is used?
Thanks!

Here is what i'm trying:
docker run --name pdns \
 --webserver=yes \
 --link pdns-mysql:mysql \
 -p 53:53 \
 -p 53:53/udp \
 -e MYSQL_USER=root \
 -e MYSQL_PASS=supersecret \
 psitrax/powerdns \
   --cache-ttl=120 \
   --allow-axfr-ips=127.0.0.1,123.1.2.3

**Comment by psi-4ward** [comment]
```
docker run --name pdns
--link pdns-mysql:mysql
-p 53:53
-p 53:53/udp
-e MYSQL_USER=root
-e MYSQL_PASS=supersecret
psitrax/powerdns
--cache-ttl=120
--allow-axfr-ips=127.0.0.1,123.1.2.3
--webserver=yes
```

is what you're searching for
