### ISSUE TITLE
sed: bad option in substitution expression

### ISSUE THREAD

**Issue by chris-topher** [psi-4ward/docker-powerdns#36]
receive this every time when running

docker run --name pdns \
>   --link pdns-mysql:mysql \
>   -p 53:53 \
>   -p 53:53/udp \
>   -e MYSQL_USER=root \
>   -e MYSQL_PASS=supersecret \
>   psitrax/powerdns \
>     --cache-ttl=120 \
>     --allow-axfr-ips=127.0.0.1,123.1.2.3

**Comment by psi-4ward** [comment]
I see. This is because docker sets the `MYSQL_PORT` to something like `tcp://172.17.0.3:3306`. You can easily overcome by setting the Port yourself, just include `-e MYSQL_PORT=3306` arg.
