### ISSUE TITLE
Missing v4.3.0 on Docker Hub 

### ISSUE THREAD

**Issue by solidnerd** [psi-4ward/docker-powerdns#48]
Hey,
I tried to pull the latest version and it's not available on docker hub.

```
docker pull psitrax/powerdns:v4.3.0
Error response from daemon: manifest for psitrax/powerdns:v4.3.0 not found: manifest unknown: manifest unknown
```

**Comment by psi-4ward** [comment]
thx for the hint, I've pushed the tags. Docker Hub should build the image in the next few hours.
