### ISSUE TITLE
How to enable API for connect PowerDNS-Admin?

### ISSUE THREAD

**Issue by 4n70w4** [psi-4ward/docker-powerdns#51]
![image](https://user-images.githubusercontent.com/38257723/92999580-b86ffd00-f52a-11ea-8dab-5e3d76a240f2.png)

**Comment by psi-4ward** [comment]
Depends on your deployment. If you are on the same docker-network you could try the name of the container.

**Comment by DamianoP** [comment]
Where is located the pdns api key ? 
Can I set it through an environment variable ? how ?

**Comment by AkgunFatih** [comment]
i am new at powedns
i need to know how i get the api key ????

**Comment by matiasah** [comment]
Hello, I have the same question. I need to connect PowerDNS Admin to PowerDNS but I'm not sure on what port I should access it as it doesn't look as it's getting exposed on the Dockerfile.
