### ISSUE TITLE
Please update PowerDNS version to 4.1.2

### ISSUE THREAD

**Issue by chinkung** [psi-4ward/docker-powerdns#9]
https://doc.powerdns.com/authoritative/changelog/4.1.html#change-4.1.2

**Comment by romracer** [comment]
@psi-4ward Any chance you could tag 4.1.2 and possibly update 4.1 and 4 on Docker Hub?  Looks like only the latest tag was updated.

**Comment by psi-4ward** [comment]
Oh I did, see https://github.com/psi-4ward/docker-powerdns/releases

I don't know why docker hub didn't recognize it this time, triggered a manual build for 4, 4.1, 4.1.2
